// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyStore_API.Data;

#nullable disable

namespace ToyStore_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyStore_API.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Dell",
                            Description = "Powerful laptop with high-resolution display.",
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 16,
                            Company = "Apple",
                            Description = "Latest smartphone with advanced camera features.",
                            Name = "Smartphone",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 3,
                            Company = "Samsung",
                            Description = "Lightweight tablet with long battery life.",
                            Name = "Tablet",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 12,
                            Company = "Sony",
                            Description = "Wireless headphones with noise-cancellation technology.",
                            Name = "Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 5,
                            Company = "Fitbit",
                            Description = "Fitness tracking smartwatch with heart rate monitor.",
                            Name = "Smartwatch",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = 18,
                            Company = "Canon",
                            Description = "Digital camera with high-quality lens.",
                            Name = "Camera",
                            Price = 599.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
